### ISSUE TITLE
Allow include paths relative to workspace folder

### ISSUE THREAD

**Issue by letmaik** [krvajal/vscode-fortran-support#132] opened 2019-05-08 18:45 UTC
I wasn't able to specify an include path relative to the workspace folder. An absolute path worked fine. I'm assuming relative paths currently don't work because the compilation is done from some random temporary folder as current working directory.

Maybe the same syntax as for launch.json could be borrowed:
`${workspaceFolder}/my/folder`.

**Comment by pedro-ricardo** [comment] 2020-02-28 22:55
This will be closed due to be a duplicate of the improvements proposed in #86

**Closed** 2020-02-28 22:55 UTC
Labels: duplicate
