### ISSUE TITLE
Add user defined snippets

### ISSUE THREAD

**Issue by gha3mi** [krvajal/vscode-fortran-support#246] opened 2021-07-13 11:59 UTC
By default there are some snippets like the program skeleton and the module skeleton. It would be interesting if users could also add or change snippets, for example by putting `fortran90.json` in `.vscode/fortran90.json` .

**Comment by gnikit** [comment] 2021-09-18 17:30
This can already be done see: https://code.visualstudio.com/docs/editor/userdefinedsnippets#_create-your-own-snippets

Duplicate of #230

**Closed by gnikit** 2021-09-18 17:30 UTC
