### ISSUE TITLE
Debugging session does not start

### ISSUE THREAD

**Issue by Farzad-Alavi** [krvajal/vscode-fortran-support#353] opened 2022-01-17 08:48 UTC
Hi,
I'm using the Modern Fortran extension for years, almost from the start. Now I can't debug FORTRAN programs, debugging session just can't start. It seems there is a conflict with other VSCode extensions. If the C++ extension pack is uninstalled, then Modern Fortran is uninstalled and reinstalled, debugging is OK as always. However, after reinstalling the C++ extension pack, the debug problem shows up.
I love Modern Fortran. Nothing left of FORTRAN IDEs, Modern Fortran extension is our only hope.
Thank you in advance

**Comment by gnikit** [comment] 2022-01-17 10:22
Could you try launching a debugger with only Modern Fortran and C++ extensions enabled.
Also could you post the versions of your Modern Fortran and C++ extensions.

Modern Fortran relies on C++ GCC debug adapter since they are virtually identical, so you always need C++ to use the Modern Fortran debugger.

**Comment by Farzad-Alavi** [comment] 2022-01-17 11:59
Thank you for your reply.
After a few hours spent on the problem, looks like there is an issue with preLaunchTask configured in "launch.json". Seems like debug session is waiting for the task, which is "build for debug" using gfortran, to complete. And it never completed!
Having Modern Fortran disabled, the task completes very quickly, build for debug is successful, and debug session starts fast.
As you suggested, all extensions were disabled, except C/C++ v1.7.1. The Modern Fortran is v2.6.2. The files "launch.json" and "tasks.json" are attached.

[vscode.zip](https://github.com/krvajal/vscode-fortran-support/files/7881658/vscode.zip)

**Comment by gnikit** [comment] 2022-01-17 14:17
So you launch.json and tasks.json seem good to me.
From what I understood the following are true:

1. Using Run and Debug from VSCode to Compile your Fortran Code and then attach it to a Debugger does not work (i.e. it hangs)
2. Running the build task on its own works
3. Using a pre compiled binary to launch a Debugger works


I tried myself a simple example (on Linux) with the same extension versions and I can't replicate the problem.

If 3 points I made above are true I would start thinking that the issue is with C++ on Windows or with your version of VSCode on Windows.

**Comment by Farzad-Alavi** [comment] 2022-01-17 17:11
All 3 points are true. Rolling back to C++ extension v1.7.0 and v1.6.0 did not solve the problem. 
The build and debug (with the same launch and task files) using g++ work perfectly. It seems the problem is somewhere in file operations by VS Code. Trying to delete a file from the currently open folder (move to recycle bin) occasionally takes a long time with a warning message.
Thank you in advance.

**Comment by gnikit** [comment] 2022-01-17 17:22
Just to give you an idea with what I am working with
I am on Linux
VS Code Insiders build 1.64.0
C++ v.1.8.0.insiders2
and Modern Fortran v3.0.0 (but this shouldn't matter for you since the Debugger is from the C++ extension)

The other thing that I would try is to recreate the tasks and launch files (delete them and ask VSCode to create a build and debug file), maybe you are missing something crucial.

Mine, again for Linux, look like this:

tasks.json
```jsonc
{
  // See https://go.microsoft.com/fwlink/?LinkId=733558
  // for the documentation about the tasks.json format
  "version": "2.0.0",
  "tasks": [
    {
      "label": "Compile Fortran",
      "type": "shell",
      "command": "gfortran",
      "args": [
        "-g",
        "-Wall",
        "${file}",
        "-o${fileDirname}/${fileBasenameNoExtension}.o"
      ],
      "problemMatcher": [],
      "group": {
        "kind": "build",
        "isDefault": true
      }
    }
  ]
}
```

launch.json
```jsonc
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "name": "(gdb) Launch Fortran",
      "type": "cppdbg",
      "request": "launch",
      "program": "${fileDirname}/${fileBasenameNoExtension}.o",
      "args": [],
      "stopAtEntry": false,
      "cwd": "${fileDirname}",
      "environment": [],
      "externalConsole": false,
      "MIMode": "gdb",
      "setupCommands": [
        {
          "description": "Enable pretty-printing for gdb",
          "text": "-enable-pretty-printing",
          "ignoreFailures": true
        },
        {
          "description": "Set Disassembly Flavor to Intel",
          "text": "-gdb-set disassembly-flavor intel",
          "ignoreFailures": true
        }
      ],
      "preLaunchTask": "Compile Fortran"
    }
  ]
}
```

**Comment by Farzad-Alavi** [comment] 2022-01-17 17:42
I'm facing this issue in both Windows 10 (21H2) and Windows 11. VS Code' about dialog shows the following info:

Version: 1.63.2 (user setup)
Commit: 899d46d82c4c95423fb7e10e68eba52050e30ba3
Date: 2021-12-15T09:40:02.816Z
Electron: 13.5.2
Chromium: 91.0.4472.164
Node.js: 14.16.0
V8: 9.1.269.39-electron.0
OS: Windows_NT x64 10.0.19044

Sorry, I can't find the path where extension's json settings file exists, but I'm pretty sure that all settings were reset to default in VS Code settings tab.

The picture below is a screenshot of the message VS Code occasionally shows on file operations. 
![image](https://user-images.githubusercontent.com/43313019/149816296-dd522254-1faa-4e98-82df-69b1ba7766fc.png)

**Comment by gnikit** [comment] 2022-01-17 17:47
I think you should raise this with the VSCode dev team https://github.com/microsoft/vscode after you check their Issues for any similar reports.

Your settings can be found by pressing `Ctrl` + `Shift` + `P` and typing Preferences: Open settings JSON.
Then search `Ctrl` + `F` for any settings containing the string `fortran.` and paste only those.

**Comment by Farzad-Alavi** [comment] 2022-01-17 20:49
The settings file contains a few lines:

{
    "python.languageServer": "Pylance",
    "debug.onTaskErrors": "showErrors"
}

I'm really confused about this issue. You're right, I have to check the VSCode issues.
Thank you in advance for your time and consideration.

**Comment by Farzad-Alavi** [comment] 2022-01-18 10:46
How about this scenario?
1. Having Modern Fortran extension installed and enabled, syntax highlighting works and breakpoints could be set. 
2. Disabling Modern Fortran extension, syntax highlight goes off, but breakpoints still remain in the open files in editor.
3. Now, all tasks including build and debug work perfectly! Variable values by mouse hover, Watch, step over, step into, and everything is fine in the debug session.
4. While debugging (e.g. stopped at a breakpoint), enabling the modern fortran extension brings back the syntax highlighting, but breaks the debug session completely, step over, and other actions are not possible.

The one and only way (for now) to debug fortran programs seems that.
It is worth mentioning that while disabling modern fortran, all file operations in VSCode are just fine. Enabling modern fortran, all trouble gets back.

**Comment by Farzad-Alavi** [comment] 2022-01-18 11:02
Till now, Modern Fortran was enabled and I was hanging around, bothering you with non-relevant issues, sorry about that. It seems to disable it resolves all problems with VSCode. By the way, C++ extension updated to v1.8.0-insiders2. Nothing changed.
Rolling back modern fortran to v.2.2.2 (a year ago) solved the problems with VSCode in Windows 10 and 11. It seems problems exist in new versions.
8 updates for modern fortran have been released in 2 months. If it helps, I can find the first version which encounter problems.
Cheers

**Comment by Farzad-Alavi** [comment] 2022-01-18 11:10
Another issue with modern fortran in Windows was that every time VSCode loaded, the message for installing fortran language server showed up. Hitting "Don't Show Again" didn't work. This message always showed up.
Actually, hitting "install now" button also did nothing!

**Comment by gnikit** [comment] 2022-01-18 11:51
The popup message issue I think was present in some older versions and has now been resolved.

If you can find the version where things broke I can have a look at the changes since I can't replicate the issue myself.

Also, when you disable the extension, do you restart VS Code?

**Comment by Farzad-Alavi** [comment] 2022-01-18 12:03
I can confirm that popup message issue still exists in v2.6.2 in latest stable release of VSCode for Windows, i.e. 1.63.2 (user setup).
After disabling modern fortran, with or without restarting VSCode, I could debug fortran programs, provided that breakpoints are set in open files in editor (because after opening VSCode, the last work environment is reloaded).
I try to find the first version which causes the issues.

**Comment by gnikit** [comment] 2022-01-18 12:41
So I have no idea why the warning fix is not working on windows, but to fix it you should set this in your settings

```json
"fortran.ignoreWarning.fortls": true
```

**Comment by Farzad-Alavi** [comment] 2022-01-18 13:07
By the way, the last version of Modern Fortran which works perfectly on my machine is 2.6.0. The problems show up from 2.6.1.
Thanks for your suggestions. I'll share my experience.
Cheers

**Comment by gnikit** [comment] 2022-01-18 18:26
Yeah that is very strange, are you sure you don't have set any other Modern Fortran settings? Because the only difference between the 2 versions is about the log channel, which was a trivial bug, see changelog

>## 2.6.1
>### Fixed
>Fixes log channel not initialising when extension fails to activate (#286)
>## 2.6.0

**Comment by Farzad-Alavi** [comment] 2022-01-19 06:08
Today an option was available for Modern Fortran extension, the great "Switch to Pre-Release Version". Once I clicked it and extension updated to v3.0.20220119, everything is perfect in both my machines running Windows 10 and 11.
In order to verify the problem with version 2.6.2, again I switch to the "Release Version" and all problems with file operations and debugging came back. Switch back to pre-release, again everything is just fine (reloaded VSCode after switch operation).
Thank you for your time and consideration. It seems everything is fine with release 3 on both Windows 10 and 11.

**Comment by Farzad-Alavi** [comment] 2022-01-19 06:12
Even the buttons in the popup message for installing FORTRAN language server are working now.

**Comment by gnikit** [comment] 2022-01-19 09:29
Awesome good to know, give the `preRelease` a go and if you have any feedback for missing features, or bugs please go ahead and Open an issue. I think that your issue might have been related to node.js actually. I seem to recall that I might have messed up the extension packaging in one of those releases, maybe I forgot to push the fix to the store and instead kept it only on the development branch.

## Notes about the preRelease

We are not relying anymore on the `fortran-language-server` Python package for the Language Server functionality. Instead we are switching to a more updated and feature-rich project called [`fortls`](https://github.com/gnikit/fortls) (which I am the author). 
I would suggest you give that a go too, you will have to first uninstall, if installed, `fortran-language-server`.

```sh
pip uninstall fortran-language-server
pip install fortls
```

Let me know if you are able to get it to work. From some local testing yesterday I seemed to be unable to get hover working on Windows.

**Comment by Farzad-Alavi** [comment] 2022-01-19 10:16
Great work. I've not installed the language server yet. I'll share my experience with fortls on Windows.

**Comment by gnikit** [comment] 2022-01-19 10:29
Okay I was being silly before. I got it to work on Windows, for `fortls` to start just make sure you have `"fortran.ignoreWarning.fortls": false` (which is set by default) AND that `"fortran.fortls.path": "C:\\your\\path\\to\\fortls.exe"` and it should work out as expected.

**Comment by gnikit** [comment] 2022-01-19 10:31
Also, an additional note, you won't be needing "FORTRAN Intellisense" anymore (if you ever had that installed)

**Comment by Farzad-Alavi** [comment] 2022-01-19 13:09
Well, thank you very much. I've already noticed that Modern Fortran is the one and only extension (if we ignore the godfather C++) I need to develop Fortran code. Also, the new icon of the extension for v3 is very good.

**Comment by gnikit** [comment] 2022-01-22 14:26
Awesome, I am glad to hear this. I will be closing this issue now. Feel free to open a new one if more issues arise.

**Closed by gnikit** 2022-01-22 14:26 UTC
