### ISSUE TITLE
Bug in syntax highlighting for nested select type

### ISSUE THREAD

**Issue by MRedies** [krvajal/vscode-fortran-support#217] opened 2021-03-04 17:20 UTC
This issue is basically https://github.com/krvajal/vscode-fortran-support/issues/181 , but instead of `select case` it's regarding `select type`:
![image](https://user-images.githubusercontent.com/6518935/110002714-00bbeb00-7d16-11eb-9c18-d501407d3655.png)

If you have a nested `select type` the syntax highlighting gets confused and doesn't highlight the 2nd `end select`. This is the test code i use:
```fortran
      SELECT TYPE(coulomb)
      CLASS is (t_mat)
         do j = 1, mpdata%n_g(ikpt)
            do i = 1, mpdata%n_g(ikpt)
               coulomb%data_c(hybdat%nbasp+i, hybdat%nbasp + j) = conjg(coul_submtx%data_c(j, i))
            enddo 
         enddo
      class is (t_mpimat)
         select type(coul_submtx)
         class is (t_mpimat)
            call coul_submtx%transpose()
            ! copy coul_submtx to bottom right corner of coulomb
            !call pzgemr2d(m,              n,               a,                  ia, ja,             desca, 
            call pzgemr2d(mpdata%n_g(ikpt),mpdata%n_g(ikpt),coul_submtx%data_c, 1, 1, coul_submtx%blacsdata%blacs_desc,&
            !             b,             ib,            jb,             descb, ictxt)
                        coulomb%data_c, hybdat%nbasp+1, hybdat%nbasp+1, coulomb%blacsdata%blacs_desc, coulomb%blacsdata%blacs_desc(2))
         class default
            call judft_error("coul_submtx should also be mpimat")
         end select
      end select
```

**Comment by gnikit** [comment] 2021-03-04 17:35
Duplicate of #181 addressed in PR #201

**Comment by gnikit** [comment] 2021-03-04 17:40
Now that I look at it more carefully, we might not have syntax highlighting support for this one.

**Comment by gnikit** [comment] 2021-03-04 18:53
So I was right, I tried your MWE and it looks fine the PR is fixing that as well.

**Closed by gnikit** 2021-03-04 18:53 UTC
