### ISSUE TITLE
Nested Switch blocks break highlighting

### ISSUE THREAD

**Issue by simplogic86** [krvajal/vscode-fortran-support#212] opened 2021-02-14 15:33 UTC
There seems to be an issue with nesting switch statements. Subsequent cases and ending lines (relative to current block) lose their highlighting. This is recursive. See below...  

![image](https://user-images.githubusercontent.com/45081142/107880936-75ce9a00-6ea7-11eb-8738-edfcf8420294.png)

**Comment by gnikit** [comment] 2021-02-14 15:44
This a duplicate of #181 and is to be merged by #201

**Closed by gnikit** 2021-02-14 15:44 UTC
