### ISSUE TITLE
"No symbols found in document" using vscode 1.41.0

### ISSUE THREAD

**Issue by cpraveen** [krvajal/vscode-fortran-support#154] opened 2019-12-16 06:35 UTC
When I open a fortran file, it does not show any symbols (function/subroutine) in the "Outline" portion on the left of the gui. This used to work for me but seems to have stopped sometime.

I have also added

```
  "fortran.symbols": ["function", "subroutine"]
```
in my settings.json file.

I am on Mac OSX Catalina with vscode version 1.41.0

**Comment by pedro-ricardo** [comment] 2019-12-16 13:21
Hello there, can you provide some example of implementation in which this happens ?
It still works for me so, I need to reproduce your problem know where it is.

If you can't send me the file, I recommend you to create a empty Fortran module and start inserting the subroutine declarations of your file in it (they can be empty, the file doesn't need to compile)...

When you create the new file the symbols are supposed to be working.. by inserting your symbols into the new file you can see when the problem starts to happen, and that is what i need to reproduce it!

Thanks

**Comment by cpraveen** [comment] 2019-12-16 13:52
I have attached a screenshot. The file opened is here

https://github.com/cpraveen/numpde/blob/master/euler1d/fortran/euler_fo.F90

I have seen this on two different machine.

I had an older version of vscode/extension on one computer and the symbols were working. I updated today morning and the symbols are not showing up.

<img width="1072" alt="Screenshot 2019-11-06 at 8 29 46 PM" src="https://user-images.githubusercontent.com/748769/70912147-589b0300-2039-11ea-8aac-a61da4d0954f.png">

**Comment by pedro-ricardo** [comment] 2019-12-16 14:26
Ok ... thanks for the file ...

But that's weird, look i have the file here and the symbols are showing
![Screenshot_2019-12-16_12-22-50](https://user-images.githubusercontent.com/15893711/70914364-9c204d80-1ff6-11ea-97b3-81aa20ac587a.png)

Can you disable all your extensions besides the Fortran one and restart the workspace to check it again ... maybe there is some conflict

**Comment by cpraveen** [comment] 2019-12-16 14:49
I disabled all other extensions and restarted vscode but that did not help.

**Comment by pedro-ricardo** [comment] 2019-12-16 15:25
Well .. Maybe VSCode changed base stuff in this new version ... Mine still 1.38.1, and this one still work.
I recommend you to downgrade yours for now because i'm unable to look into it at this moment.

Also change this issue title for something like: Symbols not working in version x.xx.x

**Comment by ReDD11** [comment] 2019-12-16 23:17
Same issue here. Restarted PC / reinstalled extension, yet the problem persists. When I toggle developper tools, it gives the following errors:
![9](https://user-images.githubusercontent.com/56961475/70951024-8a748f80-2062-11ea-8da8-d2f69888e715.png)

**Comment by pedro-ricardo** [comment] 2019-12-16 23:52
@ReDD11 Like I said before, it's likely that VSCode changed the usage of some module that involves symbols. It should be simple to fix but I don't have the time right now.

**Comment by snafumeander** [comment] 2019-12-22 08:18
Hi, I have the same problem.
It used to work well.
I didn't specify any gfortran path, only vscode 1.41 and your extension and a .f90 file with some subroutines.
The outline window will show nothing. My several computers all have the problem.
I think it's not the extension's problem, but I think you can help solving the problem.
Thanks!

**Comment by pedro-ricardo** [comment] 2020-02-24 17:31
I managed to fix it in #161, It will be merged soon.
Sorry for the long delay and thanks for reporting.

**Closed** 2020-05-15 20:43 UTC
Labels: status:fixed-waiting-merge

**Comment by mbarborini** [comment] 2022-08-10 07:37
Hello. Sorry to bother but the error is still there in version VS Code v1.70 and modern-fortran v3.2.0. Is there a workaround?

**Comment by gnikit** [comment] 2022-08-10 08:18
> Hello. Sorry to bother but the error is still there in version VS Code v1.70 and modern-fortran v3.2.0. Is there a workaround?

So symbols are working as expected. There are tests for this both in vscode and the language server.

There can be many reasons why they are not showing but for us to be able to help you will have to provide enough info to replicate the issue.

Please open a Q&A Discussion with your  - modern Fortran vscode settings
- a minimal working example for the code
- the version of fortls
- and the output of the log channel for Modern Fortran
