### ISSUE TITLE
Fixed-form syntax highlighting stops after '(' and comma OR space in column 73

### ISSUE THREAD

**Issue by Aralox** [krvajal/vscode-fortran-support#199] opened 2020-10-14 05:55 UTC
When there is a line with an open-parenthesis in it "(" and a comma in exactly line 73, syntax highlighting for all following text does not work properly. This also happens when there is a space character in column 73.
This appears to happen with fixed-form highlighting only. E.g.

`123456789_123456789_(23456789_123456789_123456789_123456789_123456789_12,)`

![image](https://user-images.githubusercontent.com/8370997/95948938-52360d00-0e3d-11eb-9fdf-0df257091a45.png)

I don't know what the problem is, but I would be happy to have a go at fixing it if I can have some help with where to look.
Thanks!

**Comment by pedro-ricardo** [comment] 2021-02-05 21:55
As pointed out previously in #87, this extension currently only supports the fixed-format syntax with the default number of characters per line as said by gfortran [here](https://gcc.gnu.org/onlinedocs/gfortran/Fortran-Dialect-Options.html)
> -ffixed-line-length-n
> Set column after which characters are ignored in typical fixed-form lines in the source file (...)
Popular values for n include 72 (the standard and the default), 80 (card image), and 132 (corresponding to “extended-source” > options in some popular compilers)

Meaning that it considers and error when the line goes beyond  72 characters, just like the compiler does by default.

**Comment by gnikit** [comment] 2021-06-02 00:09
Duplicate of #87

**Closed by gnikit** 2021-06-02 00:09 UTC
Labels: duplicate

**Comment by gnikit** [comment] 2021-06-02 00:12
Not entirely a duplicate, but both issues are requesting/noting the same thing. Which for the time being is beyond the capabilities of this extension.
