### ISSUE TITLE
Support for Intel Fortran.

### ISSUE THREAD

**Issue by hongyi-zhao** [krvajal/vscode-fortran-support#198] opened 2020-10-14 05:19 UTC
Hi,

Does this extension have the support capability for Intel Fortran?

Regards,
HY

**Comment by gnikit** [comment] 2020-10-14 07:16
As far as I know only `gfortran` can be used by the extension for linting. Of course the that doesn't mean you cannot use `ifort` to compile your project.

**Comment by hongyi-zhao** [comment] 2020-10-14 07:55
The problem is whether *gfortran* and *ifort* support exactly the same syntax/functions, and so on.

**Comment by gnikit** [comment] 2020-10-14 08:26
> The problem is whether _gfortran_ and _ifort_ support exactly the same syntax/functions, and so on.

Both of them support most of what is in the Fortran Standard. It is very well documented what parts of the standard have been implemented by Intel and GNU in their compilers, among with bugs and other issues.

There might be better references out there but here are just some quick examples:
https://web.archive.org/web/20201006084727/http://fortranwiki.org/fortran/show/Compiler+Support+for+Modern+Fortran
https://software.intel.com/content/www/us/en/develop/articles/intel-fortran-compiler-support-for-fortran-language-standards.html
https://web.archive.org/web/20200731220445/https://gcc.gnu.org/wiki/Fortran2008Status

To answer your question in short, the two compilers should be mostly the same featurewise, but the easiest way to find out is try and compile in both.

**Comment by hongyi-zhao** [comment] 2020-10-14 09:31
Thanks a lot for your comments. But IMHO, in the HPC field, say, first-principles/ab initio calculation/quantum chemistry, the popularity of intel icc/ifort compiler is much higher that of gcc/gfortran.

**Comment by gnikit** [comment] 2021-04-14 13:02
I am well aware of the popularity of propitiatory compilers in the HPC field, however this extension is not meant to and does not build your project or compile your code, you have to do that separately. Modern Fortran does not "care" what compiler you use to compile your code. The only reason why Modern Fortran utilises a compiler is to provide linting (error wiggles), for that any compiler with good support of the Fortran standard will do. Gfortran is one of these compilers.

Moreover, gfortran is open source and does not require an expensive license like ifort, which means we can use it on Circle CI for testing.

Finally, I would argue that if you need linting support for something that is not implemented by the latest version of gfortran and is by your propitiatory compiler, then you should probably be using the text editor/IDE that the propitiatory compiler ships with; for Intel on Linux that should be Eclipse.

I hope this clears things up a bit more. I will be closing this issue now, but feel free to reopen it if you have any further questions or wish to add linting support for other compilers.

**Closed by gnikit** 2021-04-14 13:02 UTC

**Comment by mobius-eng** [comment] 2021-07-09 11:58
`gfortran` unfortunately has a long standing bug with parameterized derived types (PDT). For example, it does not support type bound procedures and on some (Fortran 2003/2008 standard) code it just breaks with internal error. I guess, in order to use Intel Fortran compiler for linting, you would need to parse it output. How hard would it be to incorporate? With some help I may be able to assist as I would like to use Modern Fortran with my code that contains PDT.

**Comment by gnikit** [comment] 2021-07-11 20:11
@mobius-eng do you have a link for the bug in gfortran? I suspect if it's a common bug it would be tracked.

As for the latter part of your comment. I am afraid it is not that simple. Gfortran has a flag which does a mock compilation and outputs detailed info about the code. That's what the extension uses for linting. I recall that ifort has something similar but the  output does not adhere to the same format and hence cannot be parsed by the Modern Fortran extension.

There was someone (can't remember their username) who forked the extension with the goal of making it for ifort but I don't think that they ever got it to work.

If your code has PDTs and you want linting you might be better off with an IDE that is supported natively by the compilers Visual Studio for Windows and eclipse for Linux

**Comment by mobius-eng** [comment] 2021-07-12 05:52
@gnikit Here is the gfortran bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=82943

Support for Fortran in Visual Studio is not great either: just the syntax highlighting; the Fortran extension that is based on fortls doesn't work with Intel Fortran -- this seems to be a common thing :) .

I see the problem is rather deep... In meantime, I would just have to switch off the linter I guess.
