### ISSUE TITLE
"end" is highlighted even if it's part of a word

### ISSUE THREAD

**Issue by MRedies** [krvajal/vscode-fortran-support#41] opened 2018-03-13 14:22 UTC
![grafik](https://user-images.githubusercontent.com/6518935/37347470-3137ee20-26d2-11e8-92c2-864b9adc7845.png)

As you can see in the screenshot "append_kpts" has the "end" part highlighted, which makes little sense.

Great plugin otherwise.

**Comment by pedro-ricardo** [comment] 2018-03-13 16:43
It seems to happen only inside `type` declarations.

**Comment by krvajal** [comment] 2018-03-19 19:33
Please @MRedies, can you provide a full code snippet to reproduce the error?

**Comment by krvajal** [comment] 2018-03-19 19:54
Fixed in #42

**Closed by krvajal** 2018-03-19 19:54 UTC
Labels: syntax-highlight

**Comment by MRedies** [comment] 2018-03-20 06:42
Line 78 in 
https://github.com/MRedies/STB/blob/master/src/k_space.F90

Is this ok like this or should I get a minimal example working?

**Comment by pedro-ricardo** [comment] 2018-03-20 11:14
Hello there @MRedies, the problem is that this highlight was thought for Fortran90 and does not expect `procedure` statements inside a type definition, it keeps searching for and `end` keyword. Note that the `end type k_space` isn't highlighted because the code found the `end` earlier. @kgerheiser is currently working on a new version of the highlight code that has these features covered.

**Comment by kgerheiser** [comment] 2018-03-20 13:45
Cannot reproduce. Have you updated the extension?

**Comment by krvajal** [comment] 2018-03-20 13:46
Yes, it should be now on 1.0.1

**Comment by MRedies** [comment] 2018-03-20 13:49
My mistake. I had some weird setting. 1.01 works fine. Sorry.
