### ISSUE TITLE
Code Helper uses 100% CPU

### ISSUE THREAD

**Issue by beauof** [krvajal/vscode-fortran-support#20] opened 2018-01-04 12:41 UTC
Thanks for this incredibly helpful extension!

I have some issue when hovering over a variable. For folders with many files, instead of showing the documentation, the little pop up message just says "Loading..." and Code Helper uses 100% of my CPU.
This continues after closing Visual Studio Code and I have to force quit Code Helper to go back to normal CPU usage.

The only way to avoid this issue is to disable the extension. I would be happy if there's a fix for it, though. Maybe some setting that I am not aware of?

Visual Studio Code for Mac 1.19.1 with Modern Fortran 0.6.2 extension.

**Comment by pedro-ricardo** [comment] 2018-06-30 01:59
@krvajal Does this still happen?

**Comment by krvajal** [comment] 2018-10-14 09:10
I don't know for sure. In my case I haven't seen it. I will close this now but feel free to open it again if the problem persists.

**Comment by tgoelles** [comment] 2019-07-01 08:38
I got the same problem with Modern Fortran 2.1.0 and VS code for Mac Version 1.35.1

**Comment by pedro-ricardo** [comment] 2019-07-02 19:48
@tgoelles
Can you inform us a way to reproduce it ?
Can you isolate the problem using a fictitious file? So we can debug it without you having to share your source.

**Comment by tgoelles** [comment] 2019-07-02 20:20
It occurres when I used your extension together with Fortran IntelliSense. I then found that when I replace Modern Fortran with https://github.com/Gimly/vscode-fortran that it works. So the issue is with Modern Fortran.
The issue also only starts after a view hours of work so its hard for me to give you pointers on how to isolate the problem. 
So maybe its some incompatibility with Fortran IntelliSense. 
I will now watch more closely when the issue arises again the next time.

**Comment by gnikit** [comment] 2021-04-12 11:29
@beauof and @tgoelles are you still experiencing this problem? If so could you provide some more info about it like:
- Do you both use the fortran-language-server?
- Your extension options for Modern Fortran and if applicable FORTRAN Intellisense.
- A file and some steps to replicate the issue.

>  So the issue is with Modern Fortran.

To the best of my knowledge the only working hover support for Modern Fortran is through the FORTRAN Intellisense, which uses `fortls`, the language server protocol. The Gimly/vscode-fortran extension you pointed at does not interface with `fortls` so it normal that you are not experiencing the same issue there.

I have had the same issue in the past, but as far as I know this is not a Modern Fortran extension "issue", but a Modern Fortran Intellisense "issue". I say "issue" because this behaviour is to be expected for large, complex files.

If your file is +3k lines, has multiple dependencies and possible preprocessor variables that will cause the syntax highlighting to fail, the language server will initially struggle to provide symbols for the entire folder. 
Similarly, if you are hovering over functions/subroutines located into such file from another place in your project the first time you do that you might run into this problem. The only thing that you can do is let `fortls` work through the file. Once that's done it should store the results into cache and things should be responsive again.

If that is what is actually happening there is not much you can do other than make sure the syntax highlighting and linting does not throw any errors.

Unfortunately, as Pedro-Ricardo said, unless more information is provided for this issue there is not much we can do to help.

**Comment by beauof** [comment] 2021-04-12 18:42
@gnikit, thanks for checking in.

I am no longer a frequent Fortran developer and have stopped using vscode in combination with your extension and the Fortran code base for which the issue first occured. So I am unable to provide further details at the moment.

Thanks for your effort, though. Your extension has been very helpful!

**Comment by gnikit** [comment] 2021-04-12 19:12
Thanks for the prompt response @beauof. That is completely understandable. I think it makes sense then to close this issue now with the possibility of reopening it if any users experience similar behaviour.

**Closed by gnikit** 2021-04-12 19:12 UTC
Labels: status:needs-attention, status:waiting-for-reply

**Comment by tgoelles** [comment] 2021-04-13 06:06
Yes, I am in the same position as @beauof
