### ISSUE TITLE
Lower/Uppercase autocompletion doesnt work

### ISSUE THREAD

**Issue by PaulXiCao** [krvajal/vscode-fortran-support#96] opened 2018-11-19 14:07 UTC
The option to change the autocompletion to lowercase doesnt affect the autocompletion. It still only suggests uppercase intrinsic functions.

**Comment by pedro-ricardo** [comment] 2018-11-19 14:58
Hello There...
Since it seems to be working for me:
![screenshot_20181119_125558](https://user-images.githubusercontent.com/15893711/48714797-a2c57100-ebfa-11e8-9e9d-45ed66c2df37.png)
Can you please provide an example when it is failing? I'll look it up

**Comment by PaulXiCao** [comment] 2018-11-20 08:35
Here are two examples
![screenshot_20181120_093342](https://user-images.githubusercontent.com/25491255/48760877-8fbcaa80-eca7-11e8-94b6-f36e2c38d55d.png)
![screenshot_20181120_093415](https://user-images.githubusercontent.com/25491255/48760878-8fbcaa80-eca7-11e8-9351-e3019ad7f35c.png)

**Comment by pedro-ricardo** [comment] 2018-11-22 15:12
I just performed a clean install of VSCode, our extension and all settings to default. And still can't reproduce the outcome that you are showing.
Please verify the version of the extension you are using. It should be: 
<img width="224" alt="screenshot_20181122_125537" src="https://user-images.githubusercontent.com/15893711/48910141-50808c00-ee56-11e8-92f7-a655a8569bd5.png">
Also try to return the settings to default, maybe something is blocking the symbols.
If doesn't solve anything, disable the other extensions you have, leave just this one. The reason i say that is because that **double precision** auto complete you showed is not supported by our extension, that must be something else.
Uppon typing `dou` this is what you should see:
<img width="406" alt="screenshot_20181122_130629" src="https://user-images.githubusercontent.com/15893711/48910712-d2bd8000-ee57-11e8-8646-87ea7544e536.png">

One last thing, to get the auto-complete to work in a new the file, it must be saved first.

**Comment by FranckObspm** [comment] 2019-01-18 18:56
Hello, 

I have a similar issue. 
* change in settings of uppercase/lowercase work for intrinsic functions (ex: RANDOM_NUMBER, random_number)
* it does not seem
 to work for keywords as "program", "if", "do" etc ... 
![capture d ecran 2019-01-18 a 19 55 37](https://user-images.githubusercontent.com/15010424/51407011-0f0d1400-1b5b-11e9-8253-09aeb86e868b.png)

I am on Mac with the latest version of VSCode as well as Modern Fortran.

With my best regards

**Comment by pedro-ricardo** [comment] 2019-01-18 23:50
In fact those keywords you mentioned are out of the standard autocomplete on purpose. `program`, `if` and `do` are coded as snippets, it's symbol is that square with dots below.

Thanks for your comment @FranckObspm , I'm sure that there is somethig wrong happening, but I can't fix it because i don't see it =]. I'm very sorry.

Is there anything else you can tell me about the test you're making? Anythig can help, even the extensions you have enabled at this time.

## This is What i see here:

### Standard setting:
![screenshot_20190118_211854](https://user-images.githubusercontent.com/15893711/51418085-957c2280-1b68-11e9-979a-2c48aad39bf1.png)
**Results should be like:**
![screenshot_20190118_211835](https://user-images.githubusercontent.com/15893711/51418230-6f0ab700-1b69-11e9-8309-66129ec12c8b.png) and ![screenshot_20190118_212156](https://user-images.githubusercontent.com/15893711/51418235-75009800-1b69-11e9-8cec-0db0852f031c.png)

### Uppercase setting:
![screenshot_20190118_211919](https://user-images.githubusercontent.com/15893711/51418106-bb092c00-1b68-11e9-9ef1-3ac7b374d342.png)
**Results should be like:**
![screenshot_20190118_211933](https://user-images.githubusercontent.com/15893711/51418243-821d8700-1b69-11e9-8ca9-c35783d5cf8d.png) and ![screenshot_20190118_212141](https://user-images.githubusercontent.com/15893711/51418246-88136800-1b69-11e9-8787-6ce89f51fcfc.png)

**Comment by FranckObspm** [comment] 2019-01-19 10:59
Dear Pedro-Ricardo, thank you for your answer. 

I thought keywords as "program", "if" etc were managed on the same way than the other ones. So everything is normal. 

With my best regards

**Comment by pedro-ricardo** [comment] 2019-01-19 11:16
Humm got it :+1:
So the **bug** is that the Snippets don't obey the uppercase/lowercase settings.
I'll look into it!
It will be better if they do so.

**Comment by pedro-ricardo** [comment] 2019-02-06 11:20
I'll close this and open a new one dedicated to snippets uppercase/lowercase settings.

**Closed by pedro-ricardo** 2019-02-06 11:20 UTC
Labels: enhancement
